
  CREATE TABLE "APP"."TABELAO" 
   (	"CODIGO_OCORRENCIA2" NUMBER(38,0), 
	"AERONAVE_VOO_ORIGEM" VARCHAR2(256 BYTE), 
	"AERONAVE_VOO_DESTINO" VARCHAR2(256 BYTE), 
	"AERONAVE_FASE_OPERACAO" VARCHAR2(128 BYTE), 
	"AERONAVE_NIVEL_DANO" VARCHAR2(128 BYTE), 
	"AERONAVE_FATALIDADES_TOTAL" NUMBER(38,0), 
	"MATRICULA" VARCHAR2(128 BYTE), 
	"ASSENTOS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

